path: src
exclude-paths: ".env,.dockerignore"

type: ["Dockerfile"]
fail-on: [high, medium, low, info]
verbose: false
log-file: false

output-name: kics
output-path: .temp/reports
report-formats: html

bom: true
no-progress: true
minimal-ui: false
no-color: false
ci: false
